version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:10.14
    environment:
      POSTGRES_DB: ${RDS_DBNAME}
      POSTGRES_USER: ${RDS_USERNAME}
      POSTGRES_PASSWORD: ${RDS_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - app-data:/var/lib/postgresql/data

volumes:
  app-data:
